build-image-test:
  extends:
    - .build-image
    - .rules-image-test
  before_script:
    - export EXTRA_ARGS="--opt build-arg:CA_CRT=$CA_DIGI_CERT"
    - !reference [.build-image, before_script]
  variables:
    AUTO_PUSH: false

build-image:
  extends:
    - .build-image
  rules:
    - !reference [.rules-staging, rules]
    - !reference [.rules-production, rules]
  before_script:
    - export EXTRA_ARGS="--opt build-arg:CA_CRT=$CA_DIGI_CERT"
    - !reference [.build-image, before_script]
