openapi: 3.1.1
info:
  title: API Kepegawaian
  version: 0.1.0
  description: Dokumentasi API untuk service kepegawaian.
servers:
  - url: http://localhost:8000
tags:
  - name: Data Pribadi
paths:
  /data-pribadi:
    get:
      tags:
        - Data Pribadi
      summary: Lihat data pribadi.
      description: Lihat data pribadi dari user yang login.
      operationId: getDataPribadi
      parameters:
        - $ref: "#/components/parameters/authRequired"
      responses:
        "200":
          description: Sukses.
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    type: object
                    additionalProperties: false
                    properties:
                      id:
                        type: integer
                      nip:
                        type: string
                      nik:
                        type: string
                      tempat_lahir:
                        type: string
                      tanggal_lahir:
                        type: string
                        format: date
                      email_dikbud:
                        type: string
                      email_lain:
                        type: string
                      alamat:
                        type: string
                      nomor_hp:
                        type: string
                      agama:
                        type: string
                      jenis_kelamin:
                        type: string
                      tingkat_pendidikan:
                        type: string
                      pendidikan:
                        type: string
                      masa_kerja:
                        type: string
                      lokasi_kerja:
                        type: string
                      jenis_pegawai:
                        type: string
                      pangkat_golongan_aktif:
                        type: string
                      golongan_ruang_awal:
                        type: string
                      golongan_ruang_terakhir:
                        type: string
                      tmt_golongan:
                        type: string
                        format: date
                      gaji_pokok:
                        type: string
                      tmt_asn:
                        type: string
                        format: date
                      sk_asn:
                        type: string
                      status_pns:
                        type: string
                      kartu_pegawai:
                        type: string
                      status_perkawinan:
                        type: string
                      nomor_surat_dokter:
                        type: string
                      tanggal_surat_dokter:
                        type: string
                        format: date
                      nomor_surat_bebas_narkoba:
                        type: string
                      tanggal_surat_bebas_narkoba:
                        type: string
                        format: date
                      nomor_catatan_polisi:
                        type: string
                      tanggal_catatan_polisi:
                        type: string
                        format: date
                      akte_kelahiran:
                        type: string
                      nomor_bpjs:
                        type: string
                      npwp:
                        type: string
                      tanggal_npwp:
                        type: string
                        format: date
                      nomor_darurat:
                        type: string
                      nama:
                        type: string
                      photo:
                        type: string
                      gelar_depan:
                        type: string
                      gelar_belakang:
                        type: string
components:
  parameters:
    authRequired:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
    limit:
      name: limit
      in: query
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 50
    offset:
      name: offset
      in: query
      schema:
        type: integer
        default: 0
        minimum: 0
  schemas:
    metaPagination:
      type: object
      properties:
        limit:
          type: integer
          example: 10
          minimum: 1
          maximum: 50
        offset:
          type: integer
          example: 0
          minimum: 0
        total:
          type: integer
          example: 100
          minimum: 0
