openapi: 3.1.1
info:
  title: API Kepegawaian
  version: 0.1.0
  description: Dokumentasi API untuk service kepegawaian.
servers:
  - url: http://localhost:8000
tags:
  - name: Data Pribadi
  - name: Pelatihan Fungsional
  - name: Pelatihan Struktural
  - name: Pelatihan Teknis
  - name: Pendidikan Formal
paths:
  /data-pribadi:
    get:
      tags:
        - Data Pribadi
      summary: Lihat data pribadi.
      description: Lihat data pribadi dari user yang login.
      operationId: getDataPribadi
      parameters:
        - $ref: "#/components/parameters/authRequired"
      responses:
        "200":
          description: Sukses.
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    type: object
                    additionalProperties: false
                    properties:
                      id:
                        type: integer
                      nip:
                        type: string
                      nik:
                        type: string
                      tempat_lahir:
                        type: string
                      tanggal_lahir:
                        type: string
                        format: date
                      email_dikbud:
                        type: string
                      email_lain:
                        type: string
                      alamat:
                        type: string
                      nomor_hp:
                        type: string
                      agama:
                        type: string
                      jenis_kelamin:
                        type: string
                      tingkat_pendidikan:
                        type: string
                      pendidikan:
                        type: string
                      masa_kerja:
                        type: string
                      lokasi_kerja:
                        type: string
                      jenis_pegawai:
                        type: string
                      pangkat_golongan_aktif:
                        type: string
                      golongan_ruang_awal:
                        type: string
                      golongan_ruang_terakhir:
                        type: string
                      tmt_golongan:
                        type: string
                        format: date
                      gaji_pokok:
                        type: string
                      tmt_asn:
                        type: string
                        format: date
                      sk_asn:
                        type: string
                      status_pns:
                        type: string
                      kartu_pegawai:
                        type: string
                      status_perkawinan:
                        type: string
                      nomor_surat_dokter:
                        type: string
                      tanggal_surat_dokter:
                        type: string
                        format: date
                      nomor_surat_bebas_narkoba:
                        type: string
                      tanggal_surat_bebas_narkoba:
                        type: string
                        format: date
                      nomor_catatan_polisi:
                        type: string
                      tanggal_catatan_polisi:
                        type: string
                        format: date
                      akte_kelahiran:
                        type: string
                      nomor_bpjs:
                        type: string
                      npwp:
                        type: string
                      tanggal_npwp:
                        type: string
                        format: date
                      nomor_darurat:
                        type: string
                      nama:
                        type: string
                      photo:
                        type: string
                      gelar_depan:
                        type: string
                      gelar_belakang:
                        type: string
  /pelatihan-fungsional:
    get:
      tags:
        - Pelatihan Fungsional
      summary: Lihat daftar pelatihan fungsional.
      description: >-
        Lihat daftar pelatihan fungsional dari user yang login, urut
        berdasarkan tanggal.
      operationId: listPelatihanFungsional
      parameters:
        - $ref: "#/components/parameters/authRequired"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: Sukses.
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        jenis_diklat:
                          type: string
                        nama_diklat:
                          type: string
                        tanggal:
                          type: string
                          format: date
                        tahun:
                          type: string
                        institusi_penyelenggara:
                          type: string
                        nomor_sertifikat:
                          type: string
                  meta:
                    $ref: "#/components/schemas/metaPagination"
  /pelatihan-struktural:
    get:
      tags:
        - Pelatihan Struktural
      summary: Lihat daftar pelatihan struktural.
      description: >-
        Lihat daftar pelatihan struktural dari user yang login, urut
        berdasarkan tanggal.
      operationId: listPelatihanStruktural
      parameters:
        - $ref: "#/components/parameters/authRequired"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: Sukses.
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        nama_diklat:
                          type: string
                        nomor:
                          type: string
                        tanggal:
                          type: string
                          format: date
                        tahun:
                          type: integer
                  meta:
                    $ref: "#/components/schemas/metaPagination"
  /pelatihan-teknis:
    get:
      tags:
        - Pelatihan Teknis
      summary: Lihat daftar pelatihan teknis/seminar/workshop/kursus.
      description: >-
        Lihat daftar pelatihan teknis/seminar/workshop/kursus dari user yang
        login, urut berdasarkan tanggal.
      operationId: listPelatihanTeknis
      parameters:
        - $ref: "#/components/parameters/authRequired"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: Sukses.
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        tipe_diklat:
                          type: string
                        jenis_diklat:
                          type: string
                        nama_diklat:
                          type: string
                        jumlah_jam:
                          type: integer
                        tanggal_diklat:
                          type: string
                          format: date
                        nomor_sertifikat:
                          type: string
                  meta:
                    $ref: "#/components/schemas/metaPagination"
  /pendidikan-formal:
    get:
      tags:
        - Pendidikan Formal
      summary: Lihat daftar pendidikan formal
      description: >-
        Lihat daftar pendidikan formal dari user yang login, urut berdasarkan
        tahun lulus.
      operationId: listPendidikanFormal
      parameters:
        - $ref: "#/components/parameters/authRequired"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: Sukses.
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        jenjang_pendidikan:
                          type: string
                        nama_sekolah:
                          type: string
                        jurusan:
                          type: string
                        keterangan_pendidikan:
                          type: string
                        tahun_lulus:
                          type: string
                        nomor_ijazah:
                          type: string
                  meta:
                    $ref: "#/components/schemas/metaPagination"
components:
  parameters:
    authRequired:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
    limit:
      name: limit
      in: query
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 50
    offset:
      name: offset
      in: query
      schema:
        type: integer
        default: 0
        minimum: 0
  schemas:
    metaPagination:
      type: object
      additionalProperties: false
      properties:
        limit:
          type: integer
          example: 10
          minimum: 1
          maximum: 50
        offset:
          type: integer
          example: 0
          minimum: 0
        total:
          type: integer
          example: 100
          minimum: 0
